//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Farma24
{
    using System;
    using System.Collections.Generic;
    
    public partial class Encomenda_has_Produto
    {
        public int Encomenda { get; set; }
        public int Produto { get; set; }
        public int quantidade { get; set; }
        public double custo { get; set; }
    
        public virtual Encomenda Encomenda1 { get; set; }
        public virtual Produto Produto1 { get; set; }
    }
}
