//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Farma24
{
    using System;
    using System.Collections.Generic;
    using Farma24.Models;
    
    public partial class Morada
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Morada()
        {
            this.Encomendas = new HashSet<Encomenda>();
        }
    
        public int id { get; set; }
        public string cidade { get; set; }
        public string codPostal { get; set; }
        public string rua { get; set; }
        public string porta { get; set; }
        public string Utilizador_email { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Encomenda> Encomendas { get; set; }
        public virtual Farma24.Models.Utilizador Utilizador { get; set; }
    }
}
